### ISSUE TITLE
Twitter and facebook buttons

### ISSUE THREAD

**Issue by easybeau** [mayamcdougall/astral-pico#1]
Hello,

Very nice theme, thanks!
How do I get the twitter and facebook buttons to insert into the theme?

Thank you,
Isabelle

**Comment by mayamcdougall** [comment]
Hmm... :thinking:

I guess I didn't write that anywhere. :sweat_smile:

All you have to do is make a blank page with a `Link` variable in the metadata containing your URL.

```
---
Title: Facebook
Icon: facebook-square
Date: 2017/01/01
Link: https://facebook.com/your.user.name
---
```
Any page with a `Link` variable set will link to that URL instead of a regular page.

There are several icons in Font Awesome for each social network as well.  Facebook has `facebook` (just the f ), `facebook-official` (the official logo, with the box around it), and `facebook-square` (which has rounder edges than `official`).  Twitter has `twitter` and `twitter-square`.  You can find a complete list by searching the [Font Awesome](http://fontawesome.io/icons/) website.

I'll have to add this to the readme, because it is pretty important. :unamused:

Thanks for the question.  Hope this helps. :smile:

**Comment by easybeau** [comment]
It helped!! Thank you very much!
